# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0013_series_series_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_pic',
            field=models.CharField(default='', max_length=64),
        ),
    ]
